### ISSUE TITLE
No module named qdarktheme [OSX]

### ISSUE THREAD

**Issue by alvar036** [flutydeer/audio-slicer#19]
`Traceback (most recent call last):
  File "/Users/alvarom2/Documents/RVC/AudioslicerGUI/audio-slicer/slicer-gui.py", line 4, in <module>
    import qdarktheme
ModuleNotFoundError: No module named 'qdarktheme'`

Cloned the repo and did run requirements installation but when launching it show's this error...
how to fix this?

**Comment by flutydeer** [comment]
Check if dependencies were installed correctly, run the command below:
```
pip list
```

**Comment by alvar036** [comment]
they are:

`Last login: Sat Mar  2 12:46:03 on ttys000
(base) alvarom2@MBP-van-J-2 AudioslicerGUI % pip list
Package                 Version
----------------------- ----------
absl-py                 2.0.0
cachetools              5.3.2
certifi                 2023.11.17
cffi                    1.16.0
charset-normalizer      3.3.2
darkdetect              0.7.1
filelock                3.13.1
fsspec                  2023.12.2
google-auth             2.25.2
google-auth-oauthlib    1.2.0
grpcio                  1.60.0
idna                    3.6
Jinja2                  3.1.2
Markdown                3.5.1
MarkupSafe              2.1.3
mpmath                  1.3.0
networkx                3.2.1
numpy                   1.24.3
oauthlib                3.2.2
packaging               23.2
Pillow                  10.1.0
pip                     24.0
protobuf                4.23.4
pyasn1                  0.5.1
pyasn1-modules          0.3.0
pycparser               2.21
pyqtdarktheme           2.1.0
PySide6                 6.5.0
PySide6-Addons          6.5.0
PySide6-Essentials      6.5.0
QDarkStyle              3.2.3
QtPy                    2.4.1
requests                2.31.0
requests-oauthlib       1.3.1
rsa                     4.9
setuptools              68.2.2
shiboken6               6.5.0
six                     1.16.0
soundfile               0.12.1
sympy                   1.12
tensorboard             2.15.1
tensorboard-data-server 0.7.2
torch                   2.1.2
torchaudio              2.1.2
torchvision             0.16.2
typing_extensions       4.9.0
urllib3                 2.1.0
Werkzeug                3.0.1
wheel                   0.41.3
(base) alvarom2@MBP-van-J-2 AudioslicerGUI % 
`

**Comment by flutydeer** [comment]
Delete line 4 and line 24-34 in slicer-gui.py and try again, app can run without pyqtdarktheme

**Comment by alvar036** [comment]
thank you i tried this and got the following error:

`Traceback (most recent call last):
  File "/Users/alvarom2/Documents/RVC/AudioslicerGUI/audio-slicer/slicer-gui.py", line 8, in <module>
    import gui.mainwindow
  File "/Users/alvarom2/Documents/RVC/AudioslicerGUI/audio-slicer/gui/mainwindow.py", line 3, in <module>
    import soundfile
ModuleNotFoundError: No module named 'soundfile'`
